# root page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milms-tsilingeridis.eu-tls
spec:
  secretName: milms-tsilingeridis.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milms.tsilingeridis.eu
  dnsNames:
    - milms.tsilingeridis.eu
    # - www.milms.tsilingeridis.eu
---
# jitsi page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meet-milms-tsilingeridis.eu-tls
spec:
  secretName: meet-milms-tsilingeridis.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: meet.milms.tsilingeridis.eu
  dnsNames:
    - meet.milms.tsilingeridis.eu
    # - www.meet.milms.tsilingeridis.eu
---
# dashboard page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dsb-milms-tsilingeridis.eu-tls
spec:
  secretName: dsb-milms-tsilingeridis.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dsb.milms.tsilingeridis.eu
  dnsNames:
    - dsb.milms.tsilingeridis.eu
    # - www.dsb.milms.tsilingeridis.eu

---
# # prometheus page certificate
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: prometheus-milms-tsilingeridis.eu-tls
# spec:
#   secretName: prometheus-milms-tsilingeridis.eu
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: prometheus.milms.tsilingeridis.eu
#   dnsNames:
#     - prometheus.milms.tsilingeridis.eu
#     - www.prometheus.milms.tsilingeridis.eu
