# root page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milms-esite.gr-tls
spec:
  secretName: milms-esite.gr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milms.esite.gr
  dnsNames:
    - milms.esite.gr
    # - www.milms.esite.gr
---
# jitsi page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meet-milms-esite.gr-tls
spec:
  secretName: meet-milms-esite.gr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: meet.milms.esite.gr
  dnsNames:
    - meet.milms.esite.gr
    # - www.meet.milms.esite.gr
---
# dashboard page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dsb-milms-esite.gr-tls
spec:
  secretName: dsb-milms-esite.gr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dsb.milms.esite.gr
  dnsNames:
    - dsb.milms.esite.gr
    # - www.dsb.milms.esite.gr

---
# # prometheus page certificate
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: prometheus-milms-esite.gr-tls
# spec:
#   secretName: prometheus-milms-esite.gr
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: prometheus.milms.esite.gr
#   dnsNames:
#     - prometheus.milms.esite.gr
#     - www.prometheus.milms.esite.gr
