# root page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milms-tech-tls
spec:
  secretName: milms-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: milms.tech
  dnsNames:
    - milms.tech
    # - www.milms.tech
---
# jitsi page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meet-milms-tech-tls
spec:
  secretName: meet-milms-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: meet.milms.tech
  dnsNames:
    - meet.milms.tech
    # - www.meet.milms.tech
---
# dashboard page certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dsb-milms-tech-tls
spec:
  secretName: dsb-milms-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dsb.milms.tech
  dnsNames:
    - dsb.milms.tech
    # - www.dsb.milms.tech

---
# # prometheus page certificate
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: prometheus-milms-tech-tls
# spec:
#   secretName: prometheus-milms-tech
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: prometheus.milms.tech
#   dnsNames:
#     - prometheus.milms.tech
#     - www.prometheus.milms.tech
