apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: dev
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/non-persistent/*
build:
  # local:
  #   push: false
  artifacts:
    - image: otsili/auth
      context: backend/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: otsili/courses
      context: backend/courses
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: otsili/frontend_dev
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - src/**/*
    # - image: otsili/frontend_prod
    #   context: frontend
    #   docker:
    #     dockerfile: Dockerfile.prod
    #   sync:
    #     manual:
    #       - src: '/dist/frontend/*.js'
    #         dest: .
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: otsili/conference
    #   context: backend/conference
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     # infer:
    #     #   - src/**/*
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    - image: otsili/jitsi-meet
      context: backend/jitsi-meet
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - src/**/*
        # manual:
        #   # - src: 'src/**/*.ts'
        #   #   dest: .
---
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: pvc
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/persistent-volumes/*

# ---
# apiVersion: skaffold/v2beta11
# kind: Config
# metadata:
#   name: tls
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/tls/*

---
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: ns
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/namespaces/*

---
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: kms
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/kms/*
