# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 135.181.39.6
            - name: NFS_PATH
              value: /nfs-export
      volumes:
        - name: nfs-client-root
          nfs:
            server: 135.181.39.6
            path: /nfs-export