---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jitsi
  namespace: jitsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      volumes:
        - name: jitsi-accounts-storage
          ### for sync with the local machine ###
          # hostPath:
          #   path: /mnt/Data/milms/auth/files
          # path: /hosthome/odysseas/mnt-milms/auth/files
          ### for sync with pvc on the local machine ###
          persistentVolumeClaim:
            claimName: jitsi-accounts-pvc
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable-6726
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.milms.tech
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.milms.tech
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.milms.tech
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.milms.tech
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Athens
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
        - name: prosody
          image: jitsi/prosody:stable-6726
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: jitsi-accounts-storage
              # mountPath: /config/data/jitsi%2emilms%2etech/accounts
              mountPath: /config/data/
          env:
            - name: ENABLE_AUTH
              value: '1'
            - name: ENABLE_GUESTS
              value: '1'
            - name: AUTH_TYPE
              value: 'internal'
            - name: PUBLIC_URL
              value: 'https://meet.milms.tech'
            - name: XMPP_DOMAIN
              value: meet.milms.tech
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.milms.tech
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.milms.tech
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.milms.tech
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Athens
            - name: JVB_TCP_HARVESTER_DISABLED
              value: 'true'
        - name: web
          # image: jitsi/web:stable-6726
          image: otsili/jitsi-meet
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_URL
              value: 'https://jjitsii.milms.tech'
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: meet.milms.tech
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.milms.tech
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.milms.tech
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.milms.tech
            - name: TZ
              value: Europe/Athens
            - name: JVB_TCP_HARVESTER_DISABLED
              value: 'true'
        - name: jvb
          image: jitsi/jvb:stable-6726
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: DOCKER_HOST_ADDRESS
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.milms.tech
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.milms.tech
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.milms.tech
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: 'true'
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: '30300'
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: Europe/Athens
      serviceAccountName: jitsi
---

